# Generated by Django 5.1 on 2024-08-27 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuotePage', '0002_quote_last_y_position_alter_quote_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='Last_y_position',
        ),
    ]
