# Generated by Django 5.1 on 2024-08-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuotePage', '0003_remove_quote_last_y_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
