# Generated by Django 5.1 on 2024-08-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuotePage', '0005_quote_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='caption',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
