# Generated by Django 5.1 on 2024-08-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuotePage', '0007_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='fontcolor',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
