# Generated by Django 5.1 on 2024-08-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuotePage', '0009_quote_fontsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='fontfamily',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Courier New', 'Courier New'), ('Georgia', 'Georgia'), ('Verdana', 'Verdana')], default='Arial', max_length=50),
        ),
    ]
