# Generated by Django 5.1 on 2024-08-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuotePage', '0010_quote_fontfamily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='fontfamily',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Arial_Italic', 'Arial Italic'), ('Arial_Bold', 'Arial Bold'), ('Arial_Bold_Italic', 'Arial Bold Italic'), ('Times_New_Roman', 'Times New Roman'), ('Times_New_Roman_Italic', 'Times New Roman Italic'), ('Times_New_Roman_Bold', 'Times New Roman Bold'), ('Times_New_Roman_Bold_Italic', 'Times New Roman Bold Italic'), ('Courier_New', 'Courier New'), ('Courier_New_Italic', 'Courier New Italic'), ('Courier_New_Bold', 'Courier New Bold'), ('Courier_New__Bold_Italic', 'Courier New Bold Italic'), ('Georgia', 'Georgia'), ('Georgia_Italic', 'Georgia Italic'), ('Georgia_Bold', 'Georgia Bold'), ('Georgia_Bold_Italic', 'Georgia Bold Italic'), ('Verdana', 'Verdana'), ('Verdana_Italic', 'Verdana Italic'), ('Verdana_Bold', 'Verdana Bold'), ('Verdana_Bold_Italic', 'Verdana Bold Italic')], default='Arial', max_length=50),
        ),
    ]
