# Generated by Django 5.1 on 2024-08-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuotePage', '0015_alter_quote_fontfamily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='fontfamily',
            field=models.CharField(choices=[('arial', 'Arial'), ('ariali', 'Arial Italic'), ('arialbd', 'Arial Bold'), ('arialbi', 'Arial Bold Italic'), ('times', 'Times New Roman'), ('timesi', 'Times New Roman Italic'), ('timesbd', 'Times New Roman Bold'), ('timesbi', 'Times New Roman Bold Italic'), ('cour', 'Courier New'), ('couri', 'Courier New Italic'), ('courbd', 'Courier New Bold'), ('courbi', 'Courier New Bold Italic'), ('georgia', 'Georgia'), ('georgiai', 'Georgia Italic'), ('georgiab', 'Georgia Bold'), ('georgiaz', 'Georgia Bold Italic'), ('verdana', 'Verdana'), ('verdanai', 'Verdana Italic'), ('verdanab', 'Verdana Bold'), ('verdanaz', 'Verdana Bold Italic'), ('segoeui', 'Segoe UI'), ('segoeuib', 'Segoe UI Bold'), ('segoeuii', 'Segoe UI Italic'), ('segoeuiz', 'Segoe UI Bold Italic')], default='Arial', max_length=50),
        ),
    ]
