# Generated by Django 5.1 on 2024-08-31 04:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuotePage', '0016_alter_quote_fontfamily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
