# Generated by Django 5.1 on 2024-08-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuotePage', '0017_alter_quote_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='fontfamily',
            field=models.CharField(choices=[('arial', 'arial'), ('arialbd', 'arialbd'), ('arialbi', 'arialbi'), ('ariali', 'ariali'), ('ariblk', 'ariblk'), ('cour', 'cour'), ('courbd', 'courbd'), ('courbi', 'courbi'), ('couri', 'couri'), ('georgia', 'georgia'), ('georgiab', 'georgiab'), ('georgiai', 'georgiai'), ('georgiaz', 'georgiaz'), ('segoeui', 'segoeui'), ('segoeuib', 'segoeuib'), ('segoeuii', 'segoeuii'), ('segoeuil', 'segoeuil'), ('segoeuisl', 'segoeuisl'), ('segoeuiz', 'segoeuiz'), ('seguibl', 'seguibl'), ('seguibli', 'seguibli'), ('seguili', 'seguili'), ('seguisb', 'seguisb'), ('seguisbi', 'seguisbi'), ('seguisli', 'seguisli'), ('times', 'times'), ('timesbd', 'timesbd'), ('timesbi', 'timesbi'), ('timesi', 'timesi')], help_text='Choose a Font for Your Quote!', max_length=50),
        ),
    ]
